# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.FloatField()),
                ('avg_flowrate', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('avg_temperature', models.FloatField()),
                ('type_distribution', models.JSONField(default=dict)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='equipment.uploadeddataset')),
            ],
        ),
    ]
