# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_uploadeddataset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasummary',
            name='type_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
